services:
  postgres:
    image: postgres:16-alpine
    container_name: avaliacao-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: avaliacao
      POSTGRES_PASSWORD: avaliacao
      POSTGRES_DB: avaliacao
    ports:
      - "5432:5432"
    volumes:
      - avaliacao-pgdata:/var/lib/postgresql/data

volumes:
  avaliacao-pgdata:
